### ISSUE TITLE
Use a persistent Dynamo connection across requests

### ISSUE THREAD

**Issue by robbles** [rdegges/flask-dynamo#10]
It looks like the default behaviour of storing the connection and tables in _app_ctx_stack.top is per-request, and not persistent across multiple requests.

For optimal performance, the connection should really be re-used, as it's actually implemented as a thread-safe pool of connections in boto. Otherwise, the only re-use of connections is between multiple queries within the same request.

What do you think about changing this, possibly as a opt-in configurable behaviour? It looks like it's safe to simply store the connection in current_app.extensions['dynamo'] instead.

**Comment by rdegges** [comment]
Thank you! Initially when I wrote this, I thought that *was* a global store :(

I'd happily accept a PR to fix this =)

**Comment by robbles** [comment]
Sure, I'll take a crack at it. We've already got a custom version that does this, should be able to contribute it back somehow.
