### ISSUE TITLE
Update Docs for Boto3 Support

### ISSUE THREAD

**Issue by rdegges** [rdegges/flask-dynamo#13]
The documentation currently provides only information on using this library with boto2. The code samples should all be updated to reflect boto3 support (which is now included on the develop branch).

We should also mention that this library is Python 3 compatible.

**Comment by angadgill** [comment]
Hi @rdegges! When do you plan to release Boto3 support?

Thanks!
Angad

**Comment by rdegges** [comment]
The library supports boto3 already, just isn't documented yet. If you wanna submit some docs, a PR would be much appreciated!!
