### ISSUE TITLE
New release with the existing tables check on create_all

### ISSUE THREAD

**Issue by faidoc** [rdegges/flask-dynamo#18]
Hi

I've being struggling a bit why I was getting an error about existing tables when using the create_all method as the docs explained until I saw that the current released version doesn't include this feature, but it is already done on master in the following commit:

https://github.com/rdegges/flask-dynamo/commit/9b67ff42187bbfd3956c26e8c34a1c252cf48bb7

I'm just wondering when a new release with this fix will be commited as I need this feature on my project.

Thanks

**Comment by jaustinpage** [comment]
https://github.com/rdegges/flask-dynamo/pull/22 fixes this. It has been released to Pypi: https://pypi.python.org/pypi/flask-dynamo/0.0.8 . Marking this as closed. Thanks!
