### ISSUE TITLE
A Flask-User DBAdapter?

### ISSUE THREAD

**Issue by pjz** [rdegges/flask-dynamo#19]
Recent developments at AWS (Lambda, in particular) have me wanting to use DynamoDB for users/role/etc storage.  [Flask-User](https://github.com/lingthio/Flask-User) looked like an obvious all-in-one kind of solution, but it has no DynamoDB support.

I started writing my own using boto3 directly but then thought maybe using flask-dynamo might be a better solution... what do you suggest?  Any interest in helping out with this?

**Comment by rdegges** [comment]
DynamoDB is awesome. I love it a lottt. That said, I don't really have any time to work on new projects at the moment.

One thing you may want to consider as well -- using one of the auth-as-a-service companies. I work for one ([Stormpath](https://stormpath.com/)), and there are a bunch of other ones as well. They do this sort of thing as an API service, and have libraries already written in a bunch of languages to support exactly what you're trying to do (on AWS, too!).

=)
