### ISSUE TITLE
manager.Dynamo.init_app

### ISSUE THREAD

**Issue by tcco** [rdegges/flask-dynamo#29]
So I bumped to 0.1.1 and am running into the RuntimeError from _get_app when calling self.connection in init_app. It breaks since current_app and self.app do not return. Current app is not set since this is at load time. My question however is if self.app should be set in init_app?

My config
```
common/
    dynamo = flask_dynamo.Dynamo()

app.py
    dynamo.init_app(app)
```

**Comment by jaustinpage** [comment]
Hey, i'm taking a look now. Thanks for the report!

**Comment by jaustinpage** [comment]
Hey, I am able to reproduce. I will get a fix put together asap.

**Comment by tcco** [comment]
awesome, barring any unintended consequences I tested with just adding self.app into the init_app and it seemed to work.

**Comment by jaustinpage** [comment]
yeah, you really dont want to do that. it means that the dynamo object is now tied directly to the app instance, regardless of what the flask app context proxy is. it breaks the magic. While you can get away with it on a small scale, if you start having multiple apps doing different things, but reusing the dynamo, it can get confused. Im almost done writing tests to catch this in the future.

**Comment by jaustinpage** [comment]
if you have the ability, could you double check that https://github.com/rdegges/flask-dynamo/pull/30 fixes you?

**Comment by jaustinpage** [comment]
Ok, i think i got it fixed now.

**Comment by tcco** [comment]
understood and perfect thanks @jaustinpage

**Comment by jaustinpage** [comment]
so the branch is working for you?

**Comment by tcco** [comment]
The branch is working for me thanks! Closing out now

**Comment by jaustinpage** [comment]
https://pypi.python.org/pypi/flask-dynamo v0.1.2 is up, and includes the fix. Sorry for the bug, and thanks for reporting it!
