### ISSUE TITLE
Mocking DynamoDB

### ISSUE THREAD

**Issue by ahojukka5** [rdegges/flask-dynamo#45]
I would like to use moto to mock DynamoDB when testing my Flask app. Any hints on how this should be done? My initial attempt is:

```python
from moto import mock_dynamodb2
from flask_dynamo import Dynamo
from flask import Flask


@mock_dynamodb2
def test_init():
    app = Flask(__name__)
    dynamo = Dynamo()
    dynamo.init_app(app)
    dynamo.create_all()
    assert True
```

But this ends up to error: 

```
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost:8000/"
```

Mocking the database directly without using flask_dynamo seems to be working.

**Comment by rdegges** [comment]
I'm not sure about moto, but I added functionality to test locally against a fake service -- there are docs covering it here: https://flask-dynamo.readthedocs.io/en/latest/quickstart.html#using-dynamodb-local

**Comment by ahojukka5** [comment]
Well, that's not mocking. Yes, it's possible to install DynamoDB as a local service and test with that, but how are you then going to do unit testing in GitLab/GitHub/BitBucket?

**Comment by rdegges** [comment]
Hey there -- sorry, I misunderstood your question.

To answer your question more directly (now that I understand what you mean =D), I'm not sure. It looks like the decorator usage mocks out all of the dynamo calls. I'm not certain why that isn't working for you :(

**Comment by ahojukka5** [comment]
Well, I turned out that this was a user error. I didn't understand how to create a mock fixture. This package is working with moto just fine.

**Comment by rdegges** [comment]
Yey! I am really happy you were able to figure it out, sorry I wasn't of more use here :(
