### ISSUE TITLE
AWS access key id & secret should not be required

### ISSUE THREAD

**Issue by dcosson** [rdegges/flask-dynamo#5]
boto just "does the right thing" when running on an EC2 instance if access key id and secret are not set at all but an iam instance profile is enabled on the instance.

So it seems like [these lines](https://github.com/rdegges/flask-dynamo/blob/5b0099831b6edc5eb669180831e629ad7ecb9a0e/flask_dynamo/manager.py#L60-L61) should just be removed because these parameters aren't actually required.

Thoughts?

**Comment by boivie** [comment]
Bump**2

**Comment by rdegges** [comment]
So, I just merged in the outstanding PR which fixes this issue for the access credentials. This is now live in a new release (0.0.6), so if you upgrade you can take advantage of this in your codez.

This release also includes support for dynamically specifying the DYNAMO_TABLES setting -- so you no longer HAVE TO specify it first =)

**Comment by dcosson** [comment]
Awesome, thanks for putting those changes in!

**Comment by rdegges** [comment]
Ya! I apologize for being such a shitty maintainer! I'll be more on point in the future >:)

**Comment by boivie** [comment]
Thanks :+1:
